{
	"version": 1562591350,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/bush-sheet0.png",
		"images/spawnpoint-sheet0.png",
		"images/gameover-sheet0.png",
		"images/enemydestructible-sheet0.png",
		"images/enemydestructible-sheet1.png",
		"images/goright-sheet0.png",
		"images/goleft-sheet0.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coin-sheet2.png",
		"images/goup-sheet0.png",
		"images/godown-sheet0.png",
		"images/enemyindestructible-sheet0.png",
		"images/enemyindestructible-sheet1.png",
		"images/levelexit-sheet0.png",
		"images/checkpoint-sheet0.png",
		"images/checkpoint-sheet1.png",
		"images/checkpoint-sheet2.png",
		"images/restart-sheet0.png",
		"images/levelcomplete-sheet0.png",
		"images/continue-sheet0.png",
		"images/pressspace-sheet0.png",
		"images/gamecomplete-sheet0.png",
		"images/oscleft-sheet0.png",
		"images/oscright-sheet0.png",
		"images/oscjump-sheet0.png",
		"images/watertop-sheet0.png",
		"images/cactus-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tilemap.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/spritefont.png",
		"images/tiledoor.png",
		"images/bossl1-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/enemyboss-sheet0.png",
		"images/spritedoor-sheet0.png",
		"images/spritedoor-sheet1.png",
		"images/buildingsbg-sheet0.png",
		"images/buildingsbg4-sheet0.png",
		"images/environmentpreview-sheet0.png",
		"images/spritedialog-sheet0.png",
		"images/spritedialog-sheet1.png",
		"images/spritedialog-sheet2.png",
		"images/playerbullet-sheet0.png",
		"images/playerbullet-sheet1.png",
		"images/playerbullet-sheet2.png",
		"images/spriteenemyimpact-sheet0.png",
		"images/spriteenemyimpact-sheet1.png",
		"images/spriteenemyimpact-sheet2.png",
		"images/deathparticle.png",
		"images/sprite10-sheet0.png",
		"images/bossbullet-sheet0.png",
		"images/spidersweb-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/magiccliffspreviewx-sheet0.png",
		"images/titlebg-sheet0.png",
		"images/titlebg-sheet1.png",
		"images/titlebg-sheet2.png",
		"images/titlebg-sheet3.png",
		"images/titlebg-sheet4.png",
		"images/titlebg-sheet5.png",
		"images/titlebg-sheet6.png",
		"images/titlebg-sheet7.png",
		"images/titlebg-sheet8.png",
		"images/titlebg-sheet9.png",
		"images/titlebg-sheet10.png",
		"images/titlebg-sheet11.png",
		"images/titlebg-sheet12.png",
		"images/titlebg-sheet13.png",
		"images/titlebg-sheet14.png",
		"images/titlebg-sheet15.png",
		"images/titlebg-sheet16.png",
		"images/titlebg-sheet17.png",
		"images/titlebg-sheet18.png",
		"images/titlebg-sheet19.png",
		"images/titlebg-sheet20.png",
		"images/titlebg-sheet21.png",
		"images/titlebg-sheet22.png",
		"images/titlebg-sheet23.png",
		"images/titlebg-sheet24.png",
		"images/titlebg-sheet25.png",
		"images/titlebg-sheet26.png",
		"images/titlebg-sheet27.png",
		"images/titlebg-sheet28.png",
		"images/titlebg-sheet29.png",
		"images/sprite11-sheet0.png",
		"images/spritegroundlv2-sheet0.png",
		"images/tilemap3.png",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/die.m4a",
		"media/die.ogg",
		"media/enemy.m4a",
		"media/enemy.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/8-bit loop (loop).m4a",
		"media/8-bit loop (loop).ogg",
		"media/jingles_pizza12.m4a",
		"media/jingles_pizza12.ogg",
		"media/jingles_sax07.m4a",
		"media/jingles_sax07.ogg",
		"media/jingles_steel02.m4a",
		"media/jingles_steel02.ogg",
		"media/watery_cave_loop.ogg",
		"media/soul_yellow_fire.m4a",
		"media/soul_yellow_fire.ogg",
		"media/core_lasers.m4a",
		"media/core_lasers.ogg",
		"media/ragnarok prontera theme.m4a",
		"media/ragnarok prontera theme.ogg",
		"media/ragnarok online ost 12  streamside.ogg",
		"media/talk_sans.m4a",
		"media/talk_sans.ogg",
		"media/talk_temmie_1.m4a",
		"media/talk_temmie_1.ogg",
		"media/talk_undyne_1.m4a",
		"media/talk_undyne_1.ogg",
		"media/platformer_level03_loop.ogg",
		"media/final fantasy viii - liberi fatali [hq].ogg",
		"media/hollow knight ost - false knight.ogg",
		"media/hollow knight ost - hornet.ogg",
		"media/undertale - megalovania.ogg",
		"media/undertale mettaton ex theme  death by glamour.ogg",
		"media/undertale ost  005 - ruins.ogg",
		"media/undertale ost  006 - uwa!! so temperate♫.ogg",
		"media/undertale ost  012 - home.ogg",
		"media/undertale ost  009 - enemy approaching.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}